{
 "title": "SLOs - Ping - 28d",
 "description": "Tracks service's SLOs and error budget consumption.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "query": "simple-service" },
   { "name": "handler", "query": "/ping" }
  ]
 },
 "panels": [
  {
   "title": "Ticket Alerts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{alertstate=\"firing\",severity=\"ticket\",app=\"$app\",handler=\"$handler\"} or on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Page Alerts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{alertstate=\"firing\",severity=\"page\",app=\"$app\",handler=\"$handler\"} or on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Remaining Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "job:slo_availability:remaining_error_budget_slo95_28d{app=\"$app\",handler=\"$handler\"}",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "job:sli_availability:rate28d{app=\"$app\",handler=\"$handler\"}",
     "legendFormat": "sli"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(task:http_response_total_count{app=\"$app\",handler=\"$handler\"}[1m])) by (job,app,handler)",
       "legendFormat": "total requests rate"
      },
      {
       "expr": "sum(rate(task:http_response_error_count{handler=\"$handler\"}[1m])) by (job,app,handler)",
       "legendFormat": "error responses rate"
      }
     ]
    }
   ]
  }
 ]
}