apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prometheus
  name: prometheus-config-map
data:
  prometheus.yaml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
    - job_name: 'prometheus-scraper'

      kubernetes_sd_configs:
      - role: endpoints

      scheme: http
      metrics_path: /metrics

      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: true;admin
      - separator: ;
        regex: __meta_kubernetes_pod_label_(.+)
        replacement: $1
        action: labelmap
