apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: grafana
  name: grafana-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/kubernetes/grafana/storage