apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: grafana
  name: grafana-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: grafana
  name: grafana-db-pvc-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi