apiVersion: v1
kind: Service
metadata:
  namespace: grafana
  name: grafana-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: grafana-postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grafana
  name: grafana-postgres
  labels:
    app: grafana-postgres
spec:
  selector:
    matchLabels:
      app: grafana-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-postgres
    spec:
      containers:
        - env:
          - name: POSTGRES_DB
            value: grafana
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          name: postgres
          image: postgres:15.2
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: grafana-db-pvc