apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grafana
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:9.4.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-config-map-volume
              mountPath: /etc/grafana
            - name: grafana-storage-volume
              mountPath: /grafana/
      volumes:
        - name: grafana-config-map-volume
          configMap:
            defaultMode: 420
            name: grafana-config-map
        - name: grafana-storage-volume
          persistentVolumeClaim:
            claimName: grafana-db-pvc-grafana
---

apiVersion: v1
kind: Service
metadata:
  namespace: grafana
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - name: application
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
