apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: prometheus
  name: prometheus-storage-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/kubernetes/prometheus/storage
