apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: prometheus
  name: prometheus-storage-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: localstorage
  hostPath:
    path: /tmp
