apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prometheus
  name: prometheus-storage-pvc
spec:
  storageClassName: localstorage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
