apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prometheus
  name: prometheus-config-map
data:
  prometheus.yaml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
    - job_name: 'prometheus-scraper'

      kubernetes_sd_configs:
      - role: endpoints

      scheme: http
      metrics_path: /metrics

      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: true;admin
      - separator: ;
        regex: __meta_kubernetes_pod_label_(.+)
        replacement: $1
        action: labelmap

    rule_files:
    - "http_response.rules.yaml"
    - "sli.rules.yaml"
    - "slo.rules.yaml"
    - "slo_alert.rules.yaml"

  http_response.rules.yaml: |
    groups:
    - name: http_response_count
      rules:
        - record: task:http_response_error_count
          expr: http_requests_total{code=~"5[0-9]{2}"}

        - record: task:http_response_success_count
          expr: http_requests_total{code!~"5[0-9]{2}"}

        - record: task:http_response_total_count
          expr: http_requests_total{code=~"[0-9]{3}"}

  sli.rules.yaml: |
    groups:
      - name: sli_availability
        rules:
          - record: app_action:sli_availability:rate5m
            expr: sum by (job,app,action) (rate(task:http_response_success_count[5m])) / sum by (job,app,action) (rate(task:http_response_total_count[5m]))

          - record: app_action:sli_availability:rate30m
            expr: sum by (job,app,action) (rate(task:http_response_success_count[30m])) / sum by (job,app,action) (rate(task:http_response_total_count[30m]))

          - record: app_action:sli_availability:rate1h
            expr: sum by (job,app,action) (rate(task:http_response_success_count[1h])) / sum by (job,app,action) (rate(task:http_response_total_count[1h]))

          - record: app_action:sli_availability:rate2h
            expr: sum by (job,app,action) (rate(task:http_response_success_count[2h])) / sum by (job,app,action) (rate(task:http_response_total_count[2h]))

          - record: app_action:sli_availability:rate6h
            expr: sum by (job,app,action) (rate(task:http_response_success_count[6h])) / sum by (job,app,action) (rate(task:http_response_total_count[6h]))

          - record: app_action:sli_availability:rate24h
            expr: sum by (job,app,action) (rate(task:http_response_success_count[24h])) / sum by (job,app,action) (rate(task:http_response_total_count[24h]))

          - record: app_action:sli_availability:rate3d
            expr: sum by (job,app,action) (rate(task:http_response_success_count[3d])) / sum by (job,app,action) (rate(task:http_response_total_count[3d]))

          - record: app_action:sli_availability:rate28d
            expr: sum by (job,app,action) (rate(task:http_response_success_count[28d])) / sum by (job,app,action) (rate(task:http_response_total_count[28d]))

  slo.rules.yaml: |
    groups:
      - name: slo_availability
        rules:
          - record: app_action:sli_availability_error:rate28d
            expr: 1 - (app_action:sli_availability:rate28d)

          - record: app_action:slo_availability95_error_budget:rate28d
            expr: 1 - (app_action:sli_availability_error:rate28d / 0.05)

          - record: app_action:slo_availability99_error_budget:rate28d
            expr: 1 - (app_action:sli_availability_error:rate28d / 0.01)

  slo_alert.rules.yaml: |
    groups:
      - name: slo_availability_alert
        rules:
          - alert: slo_page
            expr: |
              ((1-app_action:sli_availability:rate1h) > (14.4*0.05) and (1-app_action:sli_availability:rate5m) > (14.4*0.05))
              or
              ((1-app_action:sli_availability:rate6h) > (6*0.05) and (1-app_action:sli_availability:rate30m) > (6*0.05))
            labels:
              severity: page

          - alert: slo_ticket
            expr: |
              ((1-app_action:sli_availability:rate24h) > (3*0.05) and (1-app_action:sli_availability:rate2h) > (3*0.05))
              or
              ((1-app_action:sli_availability:rate3d) > 0.05 and (1-app_action:sli_availability:rate6h) > 0.05)
            labels:
              severity: ticket