apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prometheus
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.42.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yaml"
            - "--storage.tsdb.path=/prometheus/"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-map-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-map-volume
          configMap:
            defaultMode: 420
            name: prometheus-config-map

        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-storage-pvc

---
apiVersion: v1
kind: Service
metadata:
  namespace: prometheus
  name: prometheus-service
  labels:
    app: prometheus
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
  type: ClusterIP
